// Mocks generated by Mockito 5.0.16 from annotations
// in gateway/test/ble/bloc/ble_connector.test.dart.
// Do not manually edit this file.

import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:reactive_ble_platform_interface/reactive_ble_platform_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDiscoveredDevice_0 extends _i1.Fake implements _i2.DiscoveredDevice {
}

/// A class which mocks [DiscoveredDevice].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockDiscoveredDevice extends _i1.Mock implements _i2.DiscoveredDevice {
  MockDiscoveredDevice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  Map<_i2.Uuid, _i3.Uint8List> get serviceData =>
      (super.noSuchMethod(Invocation.getter(#serviceData),
              returnValue: <_i2.Uuid, _i3.Uint8List>{})
          as Map<_i2.Uuid, _i3.Uint8List>);
  @override
  List<_i2.Uuid> get serviceUuids =>
      (super.noSuchMethod(Invocation.getter(#serviceUuids),
          returnValue: <_i2.Uuid>[]) as List<_i2.Uuid>);
  @override
  _i3.Uint8List get manufacturerData =>
      (super.noSuchMethod(Invocation.getter(#manufacturerData),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  int get rssi =>
      (super.noSuchMethod(Invocation.getter(#rssi), returnValue: 0) as int);
  @override
  _i2.DiscoveredDevice copyWith(
          {String? id,
          String? name,
          Map<_i2.Uuid, _i3.Uint8List>? serviceData,
          List<_i2.Uuid>? serviceUuids,
          _i3.Uint8List? manufacturerData,
          int? rssi}) =>
      (super.noSuchMethod(
          Invocation.method(#copyWith, [], {
            #id: id,
            #name: name,
            #serviceData: serviceData,
            #serviceUuids: serviceUuids,
            #manufacturerData: manufacturerData,
            #rssi: rssi
          }),
          returnValue: _FakeDiscoveredDevice_0()) as _i2.DiscoveredDevice);
  @override
  _i2.DiscoveredDevice copyUsing(
          void Function(_i2.DiscoveredDevice$Change)? mutator) =>
      (super.noSuchMethod(Invocation.method(#copyUsing, [mutator]),
          returnValue: _FakeDiscoveredDevice_0()) as _i2.DiscoveredDevice);
  @override
  String toString() => super.toString();
}
